---
title: "BMS 225A Workshop 2"
author: "Charles Shen"
date: "2023-10-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Weather Data Analysis
```{r load_library, message=FALSE}
library(tidyverse)
```

```{r Read in data}
# option + -
sf_weather <- read.csv("../raw_data/sf_weather_2023.csv")
colnames(sf_weather)
```
```{r Subset the data}
# Command + Shift + M
date <- sf_weather %>% 
  select(DATE) 
```

```{r Subset and split out data}
sf_weather_tmp <- sf_weather %>% 
  select(c("DATE","TMAX","TMIN")) %>% 
  na.omit() %>% 
  separate(DATE, c("YEAR","MONTH","DAY"), sep="-", remove=FALSE) %>% 
  filter(YEAR == "2021") %>% 
  mutate("TAVG"=((TMAX+TMIN)/2)) %>% 
  group_by(MONTH) %>% 
  summarize(MAX_MO_TEMP = max(TAVG))

summary(sf_weather_tmp)
# how to get the NA data
# sf_weather[is.na(sf_weather$TMAX),]
# this is named base R
head(sf_weather_tmp)
```

```{r}
library(ggplot2)
plot(sf_weather_tmp)
ggplot(sf_weather_tmp, aes(x=MONTH,y=MAX_MO_TEMP)) + geom_point()
```

```{r Apply functions}
yearly_subsetter <- function(year){
  year_subset <- sf_weather %>% 
    select(c("DATE","TMAX","TMIN")) %>% 
    na.omit() %>% 
    separate(DATE, c("YEAR","MONTH","DAY"), sep="-", remove=FALSE) %>% 
    filter(YEAR == year) %>% 
    mutate("TAVG"=((TMAX+TMIN)/2)) %>% 
    group_by(MONTH) %>% 
    summarize(MAX_MO_TEMP = max(TAVG))
  
  return(year_subset)
}

yearly_subsetter(2020)
```

```{r Apply function to data}
year_var <- "1980"
plot(yearly_subsetter(year_var), main = year_var)

```
```{r Apply Function with Loops, fig.height=4, fig.width=6}
for (my_year_var in c("1970","1980","1990","2000")){
  plot(yearly_subsetter(my_year_var),main=my_year_var)
}
```

